#!/usr/bin/env node
import { spawn, type ChildProcess } from "node:child_process";
import { Command } from "commander";
import { TelemetryAgent } from "./remote.js";
import { LiveProvider } from "./telemetry.js";

/** macOS: prevent idle sleep so a sleeping host doesn't punch holes in recordings. */
function startKeepAwake(enabled: boolean, log: (message: string) => void): ChildProcess | null {
  if (!enabled || process.platform !== "darwin") return null;
  try {
    const child = spawn("caffeinate", ["-i", "-m", "-s", "-w", String(process.pid)], { stdio: "ignore" });
    child.on("error", () => {});
    log("keep-awake: caffeinate running (prevents idle sleep)");
    return child;
  } catch {
    return null;
  }
}

const program = new Command();
program
  .name("ets2-record")
  .description("Stream ETS2/ATS telemetry to a LifeForge recorder server")
  .version("0.1.0");

program
  .command("agent")
  .description("stream local game telemetry to a LifeForge recorder server")
  .requiredOption("--server <url>", "LifeForge API base URL, e.g. http://host:3636")
  .option("--token <token>", "ingest token generated by the ETS2 Record module")
  .option("--interval <ms>", "frame send interval in ms", "500")
  .option("--shared-memory <name>", "shared memory name (macOS/Linux default /SCSTelemetry)")
  .option("--buffer <n>", "max telemetry messages buffered while the server is unreachable", "1000000")
  .option("--no-keep-awake", "do not prevent the host from idle-sleeping (macOS)")
  .action((opts) => {
    const agent = new TelemetryAgent(new LiveProvider(opts.sharedMemory), {
      server: opts.server,
      token: opts.token,
      intervalMs: Number(opts.interval),
      maxPending: Number(opts.buffer),
      log: (m) => console.log(`[agent] ${m}`),
    });
    console.log(`streaming to ${opts.server} (Ctrl+C to stop)`);
    console.log("start a job in-game to record");
    const keepAwake = startKeepAwake(opts.keepAwake, (m) => console.log(`[agent] ${m}`));
    const shutdown = async () => {
      keepAwake?.kill();
      await agent.stop();
      console.log("\nstopped.");
      process.exit(0);
    };
    process.on("SIGINT", () => void shutdown());
    process.on("SIGTERM", () => void shutdown());
    agent.start();
  });

program.parse();
